### ISSUE TITLE
cargo run failed

### ISSUE THREAD

**Issue by b1tg** [mardiros/rustaman#6]
# environment
mac osx 10.12.6
rustc 1.32.0-nightly (0c999ed13 2018-12-03)

# error message

```
# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `./rustaman`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by mardiros** [comment]
I've update the README to add some instructions for you here:

https://github.com/mardiros/rustaman#on-macos

**Comment by mardiros** [comment]
@b1tg 

Let me now if it is working for you please.

I'm using Linux (ArchLinux) and never try to build it on other another OS.

**Comment by b1tg** [comment]
you mean `RUST_BACKTRACE=1` rather than `RUST_TRACEBACK=1` in README?

here is the error message

```
> RUST_BACKTRACE=1 RUST_LOG=rustaman=debug cargo run   
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
     Running `target/debug/rustaman`
 INFO  rustaman > Starting Rustaman
 INFO  rustaman > Set search path: ["/Users/ch/.local/share/gtksourceview-3.0/language-specs", "/Users/ch/.gnome2/gtksourceview-1.0/language-specs", "/usr/local/share/gtksourceview-3.0/language-specs", "/usr/share/gtksourceview-3.0/language-specs", "/Users/ch/Library/Preferences/rustaman"]
 INFO  rustaman::models::workspace > Try loading workspace from file /Users/ch/Library/Preferences/rustaman/workspace.json
 DEBUG rustaman::models::workspace > File /Users/ch/Library/Preferences/rustaman/workspace.json readed (177 chars.)
 INFO  rustaman::models::workspace > Workspace loaded from file /Users/ch/Library/Preferences/rustaman/workspace.json
 INFO  rustaman::ui::menu          > Creating menu widget
 INFO  rustaman::ui::request_editor > Creating RequestView widget ""
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:95
   8: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:59
   9: <core::option::Option<T>>::unwrap
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libcore/macros.rs:20
  10: <rustaman::ui::request_editor::RequestEditor as relm::widget::Widget>::view
             at src/ui/request_editor.rs:115
  11: relm::create_widget
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/lib.rs:235
  12: <W as relm::container::ContainerWidget>::add_widget
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/container.rs:177
  13: <rustaman::ui::window::Window as relm::widget::Widget>::view
             at src/ui/window.rs:357
  14: relm::create_widget
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/lib.rs:235
  15: relm::init
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/lib.rs:319
  16: relm::run
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/lib.rs:382
  17: relm::widget::Widget::run
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/widget.rs:63
  18: rustaman::main
             at src/main.rs:40
  19: std::rt::lang_start::{{closure}}
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libstd/rt.rs:74
  20: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  21: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  22: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  23: std::rt::lang_start
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libstd/rt.rs:74
  24: rustaman::main
```


brefore first build&run rustaman, i install these package on my computer 
```
brew install gtk+3
brew install gtksourceview3
```
and add these lines to ~/.zshrc
```
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
```

**Comment by mardiros** [comment]
Yes, backtrace, I use `RUST_BACKTRACE=1 RUST_LOG=${$(basename $(pwd))/-/_}  cargo  run`

Thanks for posting it, as you can see in the backtrace:

```
 10: <rustaman::ui::request_editor::RequestEditor as relm::widget::Widget>::view
             at src/ui/request_editor.rs:115
```

which is:

```
        let lang = langmngr.get_language("rustaman-request").unwrap();
```
meant that the file `rustaman-request.lang` dow not exists in your preference directory.


Have your run those lines, or did I do a typo somewhere here ?

```
    mkdir $HOME/Library/Preferences
    cp assets/*.lang $HOME/Library/Preferences
```

Could you ouput `ls -l  $HOME/ch/Library/Preferences/rustaman/` here ?

**Comment by b1tg** [comment]
```
> ls -l ~/Library/Preferences/rustaman
total 8
-rw-r--r--  1 ch  staff  177  1  9 00:43 workspace.json
```
```
>  cat ~/Library/Preferences/rustaman/workspace.json
{
  "name": "Rustaman",
  "requests": [],
  "environments": [
    {
      "id": 1,
      "name": "Dev",
      "payload": "%YAML 1.2\n---\n",
      "status": "Active"
    }
  ]
}%
```


```
> ls -l $HOME/Library/Preferences |grep rust
drwxr-xr-x   3 ch  staff     102  1  9 00:43 rustaman
-rw-r--r--   1 ch  staff    8362  1  9 22:16 rustaman-request.lang
-rw-r--r--   1 ch  staff    1129  1  9 22:16 rustaman-response.lang
```

**Comment by b1tg** [comment]
it works now, thanks for your patient

**Comment by mardiros** [comment]
Cool \o/, could you add a screenshot here for my curiosity then close the issue ?


Furthermore, I will merge https://github.com/mardiros/rustaman/pull/7
I've written a dedicated GTKSourceView theme for color concistancy between json, yaml, http queries
and so on.

It will add another file in the configuration directory and you will have to rerun `cp assets/* $HOME/Library/Preferences/rustaman` after that...

If you have question, let me now, I don't have write any documentation yet nor example.

It works like Insomnia but the HTTP query is really raw in the main editor.

You can use `{{ var }}` to get a var from the environment.

But, you can also use `{{ set foo="bar", bar="baz" }}` in the query as well ! (Which is a missing feature in insomnia in fact.

You can also use `{{encode var}}` to url encode a variable, for exemple
```
{{ 
 set search_value = "something that should be encoded!"
  }}

GET {{api_endpoint}}/search?what={{encode search_value}}
Authorization: bearer {{api_token}}

```
Last feature is in the environment,

there is a special key `__obfuscated__` that can be used  like this

```
api_token: "asdofiqwefqwezsd"
__obfuscated__:
    - api_token
```

In that case, the query

```
>>> New Request
! Connecting to: XXX

GET /api/v5/search?name=something+that+should+be+encoded%21 HTTP/1.1
Authorization: bearer asd...
```

I use the log edit to copy/paste stuff and don't want to leak secret...

One last things you may know is allowing insecure server connections when using SSL,
Just add the directive on the header
```
#! AllowInsecureCertificate

```
Hope it helps

**Comment by mardiros** [comment]
Ok, thanks !

So it miss some icons actually...
Your gtk install may not be complete...
